# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20180711_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverdata',
            name='urllink',
            field=models.TextField(),
        ),
    ]
